In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [726]:
df_train = pd.read_excel('Data_Train.xlsx')
df_test = pd.read_excel('Test_set.xlsx')
display(df_train.head(3))
display(df_test.head(3))

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included

In [727]:
final_df = df_train.append(df_test)
display(final_df.head(3))
display(final_df.tail(3))

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [728]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.2+ MB

In [729]:
final_df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [730]:
final_df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

## Handling datetime columns

In [731]:
final_df["Date_of_Journey"].head()

0    24/03/2019
1     1/05/2019
2     9/06/2019
3    12/05/2019
4    01/03/2019
Name: Date_of_Journey, dtype: object

In [732]:
 final_df['Date_of_Journey'].str.split('/').str[0]

0       24
1        1
2        9
3       12
4       01
        ..
2666     6
2667    27
2668     6
2669     6
2670    15
Name: Date_of_Journey, Length: 13354, dtype: object

In [733]:
# handling Date_of_Journey
final_df["Date_of_Journey_Day"] = final_df['Date_of_Journey'].str.split('/').str[0]
final_df["Date_of_Journey_Month"] = final_df['Date_of_Journey'].str.split('/').str[1]
final_df["Date_of_Journey_Year"] = final_df['Date_of_Journey'].str.split('/').str[2]

In [734]:
# changing type to integer
final_df["Date_of_Journey_Day"] = final_df['Date_of_Journey_Day'].astype(int)
final_df["Date_of_Journey_Month"] = final_df['Date_of_Journey_Month'].astype(int)
final_df["Date_of_Journey_Year"] = final_df['Date_of_Journey_Year'].astype('int')

In [735]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13354 non-null  object
 1   Date_of_Journey        13354 non-null  object
 2   Source                 13354 non-null  object
 3   Destination            13354 non-null  object
 4   Route                  13353 non-null  object
 5   Dep_Time               13354 non-null  object
 6   Arrival_Time           13354 non-null  object
 7   Duration               13354 non-null  object
 8   Total_Stops            13353 non-null  object
 9   Additional_Info        13354 non-null  object
 10  Price                  10683 non-null  float64
 11  Date_of_Journey_Day    13354 non-null  int32
 12  Date_of_Journey_Month  13354 non-null  int32
 13  Date_of_Journey_Year   13354 non-null  int32
dtypes: float64(1), int32(3), object(10)
memory usage: 1.4+ MB

In [736]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13354 non-null  object
 1   Date_of_Journey        13354 non-null  object
 2   Source                 13354 non-null  object
 3   Destination            13354 non-null  object
 4   Route                  13353 non-null  object
 5   Dep_Time               13354 non-null  object
 6   Arrival_Time           13354 non-null  object
 7   Duration               13354 non-null  object
 8   Total_Stops            13353 non-null  object
 9   Additional_Info        13354 non-null  object
 10  Price                  10683 non-null  float64
 11  Date_of_Journey_Day    13354 non-null  int32
 12  Date_of_Journey_Month  13354 non-null  int32
 13  Date_of_Journey_Year   13354 non-null  int32
dtypes: float64(1), int32(3), object(10)
memory usage: 1.4+ MB

In [737]:
# removing this column as this is useless now
final_df.drop('Date_of_Journey', axis=1, inplace=True)
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [738]:
# handling Arrival_Time
final_df['Arrival_Time_Hour'] = final_df.Arrival_Time.str.split(' ').str[0].str.split(':').str[0]
final_df['Arrival_Time_Minute'] = final_df.Arrival_Time.str.split(' ').str[0].str.split(':').str[1]

In [739]:
# changing type to integer
final_df["Arrival_Time_Hour"] = final_df['Arrival_Time_Hour'].astype(int)
final_df["Arrival_Time_Minute"] = final_df['Arrival_Time_Minute'].astype(int)

In [740]:
# handling Dep_Time
final_df['Dep_Time_Hour'] = final_df.Dep_Time.str.split(' ').str[0].str.split(':').str[0]
final_df['Dep_Time_Minute'] = final_df.Dep_Time.str.split(' ').str[0].str.split(':').str[1]

In [741]:
# changing type to integer
final_df["Dep_Time_Hour"] = final_df['Dep_Time_Hour'].astype(int)
final_df["Dep_Time_Minute"] = final_df['Dep_Time_Minute'].astype(int)

In [742]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13354 non-null  object
 1   Source                 13354 non-null  object
 2   Destination            13354 non-null  object
 3   Route                  13353 non-null  object
 4   Dep_Time               13354 non-null  object
 5   Arrival_Time           13354 non-null  object
 6   Duration               13354 non-null  object
 7   Total_Stops            13353 non-null  object
 8   Additional_Info        13354 non-null  object
 9   Price                  10683 non-null  float64
 10  Date_of_Journey_Day    13354 non-null  int32
 11  Date_of_Journey_Month  13354 non-null  int32
 12  Date_of_Journey_Year   13354 non-null  int32
 13  Arrival_Time_Hour      13354 non-null  int32
 14  Arrival_Time_Minute    13354 non-null  int32
 15  Dep_Time_Hour          13354 non-null  int32
 16  Dep_Time_Minute        13354 non-null  int32
dtypes: float64(1), int32(7), object(9)
memory usage: 1.5+ MB

In [743]:
# removing the necessary columns 
final_df.drop(columns=['Arrival_Time', 'Dep_Time'], inplace=True)

In [744]:
final_df.head(3)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25

In [745]:
final_df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date_of_Journey_Day',
       'Date_of_Journey_Month', 'Date_of_Journey_Year', 'Arrival_Time_Hour',
       'Arrival_Time_Minute', 'Dep_Time_Hour', 'Dep_Time_Minute'],
      dtype='object')

In [746]:
# getting the columns having object type
[feature for feature in final_df.columns if final_df[feature].dtype=='O']

['Airline',
 'Source',
 'Destination',
 'Route',
 'Duration',
 'Total_Stops',
 'Additional_Info']

In [747]:
final_df.drop(columns='Route', axis=1, inplace=True)

In [748]:
final_df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date_of_Journey_Day',
       'Date_of_Journey_Month', 'Date_of_Journey_Year', 'Arrival_Time_Hour',
       'Arrival_Time_Minute', 'Dep_Time_Hour', 'Dep_Time_Minute'],
      dtype='object')

In [749]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50

In [750]:
# handling Duration
final_df['Duration_Hour'] = final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [751]:
final_df['Duration_Minute'] = final_df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [752]:
final_df['Duration_Minute'].fillna(0,inplace=True)

In [753]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13354 non-null  object
 1   Source                 13354 non-null  object
 2   Destination            13354 non-null  object
 3   Duration               13354 non-null  object
 4   Total_Stops            13353 non-null  object
 5   Additional_Info        13354 non-null  object
 6   Price                  10683 non-null  float64
 7   Date_of_Journey_Day    13354 non-null  int32
 8   Date_of_Journey_Month  13354 non-null  int32
 9   Date_of_Journey_Year   13354 non-null  int32
 10  Arrival_Time_Hour      13354 non-null  int32
 11  Arrival_Time_Minute    13354 non-null  int32
 12  Dep_Time_Hour          13354 non-null  int32
 13  Dep_Time_Minute        13354 non-null  int32
 14  Duration_Hour          13354 non-null  object
 15  Duration_Minute        13354 non-null  object
dtypes: float64(1), int32(7), object(8)
memory usage: 1.4+ MB

In [754]:
# changing type to integer
final_df["Duration_Hour"] = final_df['Duration_Hour'].astype(int)
final_df["Duration_Minute"] = final_df['Duration_Minute'].astype(int)

ValueError: invalid literal for int() with base 10: '5m'

In [755]:
final_df[final_df['Duration_Hour']=='5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
6474,Air India,Mumbai,Hyderabad,5m,2 stops,No info,17327.0,6,3,2019,16,55,16,50,5m,0
2660,Air India,Mumbai,Hyderabad,5m,2 stops,No info,NaN,12,3,2019,16,55,16,50,5m,0

In [756]:
final_df.drop([6474,2660], inplace=True)

In [757]:
final_df[final_df['Duration_Hour']=='5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date_of_Journey_Day, Date_of_Journey_Month, Date_of_Journey_Year, Arrival_Time_Hour, Arrival_Time_Minute, Dep_Time_Hour, Dep_Time_Minute, Duration_Hour, Duration_Minute]
Index: []

In [758]:
# changing type to integer
final_df["Duration_Hour"] = final_df['Duration_Hour'].astype(int)
final_df["Duration_Minute"] = final_df['Duration_Minute'].astype(int)

In [759]:
# removing Duration column
final_df.drop('Duration', axis=1, inplace=True)

In [760]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13351 non-null  object
 1   Source                 13351 non-null  object
 2   Destination            13351 non-null  object
 3   Total_Stops            13350 non-null  object
 4   Additional_Info        13351 non-null  object
 5   Price                  10681 non-null  float64
 6   Date_of_Journey_Day    13351 non-null  int32
 7   Date_of_Journey_Month  13351 non-null  int32
 8   Date_of_Journey_Year   13351 non-null  int32
 9   Arrival_Time_Hour      13351 non-null  int32
 10  Arrival_Time_Minute    13351 non-null  int32
 11  Dep_Time_Hour          13351 non-null  int32
 12  Dep_Time_Minute        13351 non-null  int32
 13  Duration_Hour          13351 non-null  int32
 14  Duration_Minute        13351 non-null  int32
dtypes: float64(1), int32(9), object(5)
memory usage: 1.2+ MB

In [761]:
final_df.Total_Stops.unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [762]:
# one hot encoding
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,
                                                     '1 stop':1,
                                                     '2 stops':2,
                                                     '3 stops':3,
                                                     '4 stops':4,
                                                     'NaN':1})

In [763]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13351 non-null  object
 1   Source                 13351 non-null  object
 2   Destination            13351 non-null  object
 3   Total_Stops            13350 non-null  float64
 4   Additional_Info        13351 non-null  object
 5   Price                  10681 non-null  float64
 6   Date_of_Journey_Day    13351 non-null  int32
 7   Date_of_Journey_Month  13351 non-null  int32
 8   Date_of_Journey_Year   13351 non-null  int32
 9   Arrival_Time_Hour      13351 non-null  int32
 10  Arrival_Time_Minute    13351 non-null  int32
 11  Dep_Time_Hour          13351 non-null  int32
 12  Dep_Time_Minute        13351 non-null  int32
 13  Duration_Hour          13351 non-null  int32
 14  Duration_Minute        13351 non-null  int32
dtypes: float64(2), int32(9), object(4)
memory usage: 1.2+ MB

In [764]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [765]:
# label encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
final_df['Airline'] = label_encoder.fit_transform(final_df['Airline'])
final_df['Source'] = label_encoder.fit_transform(final_df['Source'])
final_df['Destination'] = label_encoder.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = label_encoder.fit_transform(final_df['Additional_Info'])

In [766]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,3,0,5,0.0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2.0,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2.0,8,13882.0,9,6,2019,4,25,9,25,19,0
3,3,3,0,1.0,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1.0,8,13302.0,1,3,2019,21,35,16,50,4,45

In [767]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13351 non-null  int32
 1   Source                 13351 non-null  int32
 2   Destination            13351 non-null  int32
 3   Total_Stops            13350 non-null  float64
 4   Additional_Info        13351 non-null  int32
 5   Price                  10681 non-null  float64
 6   Date_of_Journey_Day    13351 non-null  int32
 7   Date_of_Journey_Month  13351 non-null  int32
 8   Date_of_Journey_Year   13351 non-null  int32
 9   Arrival_Time_Hour      13351 non-null  int32
 10  Arrival_Time_Minute    13351 non-null  int32
 11  Dep_Time_Hour          13351 non-null  int32
 12  Dep_Time_Minute        13351 non-null  int32
 13  Duration_Hour          13351 non-null  int32
 14  Duration_Minute        13351 non-null  int32
dtypes: float64(2), int32(13)
memory usage: 990.9 KB

In [768]:
final_df[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
9039,1,2,1,NaN,8,7480.0,6,5,2019,9,25,9,45,23,40

In [769]:
final_df['Total_Stops'] = final_df['Total_Stops'].fillna(0)

In [770]:
final_df[final_df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Total_Stops, Additional_Info, Price, Date_of_Journey_Day, Date_of_Journey_Month, Date_of_Journey_Year, Arrival_Time_Hour, Arrival_Time_Minute, Dep_Time_Hour, Dep_Time_Minute, Duration_Hour, Duration_Minute]
Index: []

In [771]:
final_df['Total_Stops'] = final_df['Total_Stops'].astype(int)

In [772]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13351 non-null  int32
 1   Source                 13351 non-null  int32
 2   Destination            13351 non-null  int32
 3   Total_Stops            13351 non-null  int32
 4   Additional_Info        13351 non-null  int32
 5   Price                  10681 non-null  float64
 6   Date_of_Journey_Day    13351 non-null  int32
 7   Date_of_Journey_Month  13351 non-null  int32
 8   Date_of_Journey_Year   13351 non-null  int32
 9   Arrival_Time_Hour      13351 non-null  int32
 10  Arrival_Time_Minute    13351 non-null  int32
 11  Dep_Time_Hour          13351 non-null  int32
 12  Dep_Time_Minute        13351 non-null  int32
 13  Duration_Hour          13351 non-null  int32
 14  Duration_Minute        13351 non-null  int32
dtypes: float64(1), int32(14)
memory usage: 938.7 KB

In [773]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,3,0,5,0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2,8,13882.0,9,6,2019,4,25,9,25,19,0
3,3,3,0,1,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1,8,13302.0,1,3,2019,21,35,16,50,4,45

### One Hot Encoding for Airline, Source, Destination and Additional Info columns

In [774]:
test_df=final_df.copy()
prev_df = final_df.copy()

In [775]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                13351 non-null  int32
 1   Source                 13351 non-null  int32
 2   Destination            13351 non-null  int32
 3   Total_Stops            13351 non-null  int32
 4   Additional_Info        13351 non-null  int32
 5   Price                  10681 non-null  float64
 6   Date_of_Journey_Day    13351 non-null  int32
 7   Date_of_Journey_Month  13351 non-null  int32
 8   Date_of_Journey_Year   13351 non-null  int32
 9   Arrival_Time_Hour      13351 non-null  int32
 10  Arrival_Time_Minute    13351 non-null  int32
 11  Dep_Time_Hour          13351 non-null  int32
 12  Dep_Time_Minute        13351 non-null  int32
 13  Duration_Hour          13351 non-null  int32
 14  Duration_Minute        13351 non-null  int32
dtypes: float64(1), int32(14)
memory usage: 938.7 KB

In [776]:
test_df['Airline']

0       3
1       1
2       4
3       3
4       3
       ..
2666    1
2667    3
2668    4
2669    1
2670    6
Name: Airline, Length: 13351, dtype: int32

In [777]:
type(test_df['Airline'].head())

pandas.core.series.Series

In [778]:
test_df['Airline'].head()

0    3
1    1
2    4
3    3
4    3
Name: Airline, dtype: int32

In [779]:
test_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,3,0,5,0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2,8,13882.0,9,6,2019,4,25,9,25,19,0
3,3,3,0,1,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1,8,13302.0,1,3,2019,21,35,16,50,4,45

In [780]:
test_df['Airline'].to_numpy().reshape(-1, 1)

array([[3],
       [1],
       [4],
       ...,
       [4],
       [1],
       [6]])

In [781]:
test_df['Airline'].unique()

array([ 3,  1,  4,  8,  6,  2, 10,  0, 11,  5,  7,  9])

In [782]:
from sklearn.preprocessing import OneHotEncoder

In [783]:
# One Hot encoding
Airline_onehot_encoder_obj = OneHotEncoder(sparse=False)
Airline_onehot_encoder = Airline_onehot_encoder_obj.fit_transform(test_df['Airline'].to_numpy().reshape(-1, 1))

Source_onehot_encoder_obj = OneHotEncoder(sparse=False)
Source_onehot_encoder = Source_onehot_encoder_obj.fit_transform(test_df['Source'].to_numpy().reshape(-1, 1))

Destination_onehot_encoder_obj = OneHotEncoder(sparse=False)
Destination_onehot_encoder = Destination_onehot_encoder_obj.fit_transform(test_df['Destination'].to_numpy().reshape(-1, 1))

Additional_Info_onehot_encoder_obj = OneHotEncoder(sparse=False)
Additional_Info_onehot_encoder = Additional_Info_onehot_encoder_obj.fit_transform(test_df['Additional_Info'].to_numpy().reshape(-1, 1))

In [784]:
# this works as well
# onehot_encoder1 = onehot_encoder_obj.fit_transform(np.array(test_df['Airline']).reshape(-1, 1))

In [785]:
Airline_onehot_encoder

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [786]:
Airline_onehot_encoder.shape

(13351, 12)

In [787]:
type(Airline_onehot_encoder)

numpy.ndarray

In [788]:
type(Source_onehot_encoder)

numpy.ndarray

In [789]:
Airline_onehot_encoder_obj.get_feature_names(['Airline'])

array(['Airline_0', 'Airline_1', 'Airline_2', 'Airline_3', 'Airline_4',
       'Airline_5', 'Airline_6', 'Airline_7', 'Airline_8', 'Airline_9',
       'Airline_10', 'Airline_11'], dtype=object)

In [790]:
Additional_Info_onehot_encoder_obj.get_feature_names(['Additional_Info'])

array(['Additional_Info_0', 'Additional_Info_1', 'Additional_Info_2',
       'Additional_Info_3', 'Additional_Info_4', 'Additional_Info_5',
       'Additional_Info_6', 'Additional_Info_7', 'Additional_Info_8',
       'Additional_Info_9'], dtype=object)

In [791]:
test_df['Additional_Info'].nunique()

10

In [792]:
test_df['Airline'].nunique()

12

In [793]:
test_df['Airline'].head()

0    3
1    1
2    4
3    3
4    3
Name: Airline, dtype: int32

In [794]:
# dataframes for each encoding

airline_df = pd.DataFrame(
    Airline_onehot_encoder, # encoder
    columns = Airline_onehot_encoder_obj.get_feature_names(['Airline'])
)

source_df = pd.DataFrame(
    Source_onehot_encoder,
    columns = Source_onehot_encoder_obj.get_feature_names(['Source'])
)

destination_df = pd.DataFrame(
    Destination_onehot_encoder,
    columns = Destination_onehot_encoder_obj.get_feature_names(['Destination'])
)

additional_info_df = pd.DataFrame(
    Additional_Info_onehot_encoder,
    columns = Additional_Info_onehot_encoder_obj.get_feature_names(['Additional_Info'])
)

In [795]:
final_df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,3,0,5,0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2,8,13882.0,9,6,2019,4,25,9,25,19,0
3,3,3,0,1,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1,8,13302.0,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2666,1,3,0,1,8,NaN,6,6,2019,20,25,20,30,23,55
2667,3,3,0,0,8,NaN,27,3,2019,16,55,14,20,2,35
2668,4,2,1,1,8,NaN,6,3,2019,4,25,21,50,6,35
2669,1,2,1,1,8,NaN,6,3,2019,19,15,4,0,15,15
2670,6,2,1,1,8,NaN,15,6,2019,19,15,4,55,14,20

In [796]:
# final_df.index.is_unique
final_df.drop(columns=['Airline', 'Source', 'Destination', 'Additional_Info'], inplace=True, axis=1)
final_df.reset_index(drop=True, inplace=True)

In [797]:
final_df.head()

,Total_Stops,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,Duration_Minute
0,0,3897.0,24,3,2019,1,10,22,20,2,50
1,2,7662.0,1,5,2019,13,15,5,50,7,25
2,2,13882.0,9,6,2019,4,25,9,25,19,0
3,1,6218.0,12,5,2019,23,30,18,5,5,25
4,1,13302.0,1,3,2019,21,35,16,50,4,45

In [799]:
final_df = pd.concat([final_df, airline_df, source_df, destination_df, additional_info_df], axis=1)

In [800]:
final_df.head()

,Total_Stops,Price,Date_of_Journey_Day,Date_of_Journey_Month,Date_of_Journey_Year,Arrival_Time_Hour,Arrival_Time_Minute,Dep_Time_Hour,Dep_Time_Minute,Duration_Hour,...,Additional_Info_0,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,0,3897.0,24,3,2019,1,10,22,20,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,7662.0,1,5,2019,13,15,5,50,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,13882.0,9,6,2019,4,25,9,25,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6218.0,12,5,2019,23,30,18,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,13302.0,1,3,2019,21,35,16,50,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [801]:
final_df.index.is_unique

True

In [802]:
final_df.columns

Index(['Total_Stops', 'Price', 'Date_of_Journey_Day', 'Date_of_Journey_Month',
       'Date_of_Journey_Year', 'Arrival_Time_Hour', 'Arrival_Time_Minute',
       'Dep_Time_Hour', 'Dep_Time_Minute', 'Duration_Hour', 'Duration_Minute',
       'Airline_0', 'Airline_1', 'Airline_2', 'Airline_3', 'Airline_4',
       'Airline_5', 'Airline_6', 'Airline_7', 'Airline_8', 'Airline_9',
       'Airline_10', 'Airline_11', 'Source_0', 'Source_1', 'Source_2',
       'Source_3', 'Source_4', 'Destination_0', 'Destination_1',
       'Destination_2', 'Destination_3', 'Destination_4', 'Destination_5',
       'Additional_Info_0', 'Additional_Info_1', 'Additional_Info_2',
       'Additional_Info_3', 'Additional_Info_4', 'Additional_Info_5',
       'Additional_Info_6', 'Additional_Info_7', 'Additional_Info_8',
       'Additional_Info_9'],
      dtype='object')

In [804]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13351 entries, 0 to 13350
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Total_Stops            13351 non-null  int32
 1   Price                  10681 non-null  float64
 2   Date_of_Journey_Day    13351 non-null  int32
 3   Date_of_Journey_Month  13351 non-null  int32
 4   Date_of_Journey_Year   13351 non-null  int32
 5   Arrival_Time_Hour      13351 non-null  int32
 6   Arrival_Time_Minute    13351 non-null  int32
 7   Dep_Time_Hour          13351 non-null  int32
 8   Dep_Time_Minute        13351 non-null  int32
 9   Duration_Hour          13351 non-null  int32
 10  Duration_Minute        13351 non-null  int32
 11  Airline_0              13351 non-null  float64
 12  Airline_1              13351 non-null  float64
 13  Airline_2              13351 non-null  float64
 14  Airline_3              13351 non-null  float64
 15  Airline_4              13351 non-null  float64
 16  Airline_5              13351 non-null  float64
 17  Airline_6              13351 non-null  float64
 18  Airline_7              13351 non-null  float64
 19  Airline_8              13351 non-null  float64
 20  Airline_9              13351 non-null  float64
 21  Airline_10             13351 non-null  float64
 22  Airline_11             13351 non-null  float64
 23  Source_0               13351 non-null  float64
 24  Source_1               13351 non-null  float64
 25  Source_2               13351 non-null  float64
 26  Source_3               13351 non-null  float64
 27  Source_4               13351 non-null  float64
 28  Destination_0          13351 non-null  float64
 29  Destination_1          13351 non-null  float64
 30  Destination_2          13351 non-null  float64
 31  Destination_3          13351 non-null  float64
 32  Destination_4          13351 non-null  float64
 33  Destination_5          13351 non-null  float64
 34  Additional_Info_0      13351 non-null  float64
 35  Additional_Info_1      13351 non-null  float64
 36  Additional_Info_2      13351 non-null  float64
 37  Additional_Info_3      13351 non-null  float64
 38  Additional_Info_4      13351 non-null  float64
 39  Additional_Info_5      13351 non-null  float64
 40  Additional_Info_6      13351 non-null  float64
 41  Additional_Info_7      13351 non-null  float64
 42  Additional_Info_8      13351 non-null  float64
 43  Additional_Info_9      13351 non-null  float64
dtypes: float64(34), int32(10)
memory usage: 4.0 MB